apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streaming-api
  namespace: streaming
spec:
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: streaming-api
        serviceName: streaming-api
    spec:
      containers:
      - name: streaming-api
        image: index.docker.io/mateuszdyminski/streaming:latest
        ports:
          - containerPort: 8080
        resources:
            limits:
              memory: 100Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 200m
      imagePullSecrets:
        - name: docker-reg